version: '2'
services:
  database:
    image: "daocloud.io/library/mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=5ecret
      - MYSQL_USER=17high
      - MYSQL_PASSWORD=17high
      - MYSQL_DATABASE=17high
    volumes:
      - ~/17high/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  backup:
    image: "daocloud.io/wjyao/mysql-backup-s3"
    environment:
      - S3_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET=17high-new
      - MYSQLDUMP_DATABASE=17high
      - MYSQL_HOST=database
      - MYSQL_USER=17high
      - MYSQL_PASSWORD=17high
      - S3_REGION=cn-north-1
      - MULTI_FILES=yes
      - SCHEDULE=@daily
    links:
      - database
  17high:
    image: "registry.cn-hangzhou.aliyuncs.com/wjyao/17high_web"
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=17high
      - MYSQL_USER=17high
      - MYSQL_PASSWORD=17high
      - VIRTUAL_HOST=17high.twer.vip
    volumes:
      - ~/17high/app/tmp:/tmp
    links:
      - database

  nginx:
    image: jwilder/nginx-proxy
    volumes:
      - ~/17high/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
      - "443:443"
